services:
  frontend:
    container_name: frontend
    image: frontend
    restart: always
    build:
      context: ./frontend
      dockerfile: frontend.dockerfile
    ports:
      - 80:80
    depends_on:
      - backend 

  backend:
    container_name: backend
    image: backend
    build:
      context: ./backend
      dockerfile: backend.dockerfile
    ports:
      - 8080:8080
    environment:
      DATABASE_URL: postgresql://admin:admin1234@database:5432/mydb?schema=public 
      GOOGLE_API_URL: https://routes.googleapis.com/directions
      GOOGLE_API_KEY: ${GOOGLE_API_KEY}
    env_file:
      - .env
    depends_on:
      - database
    volumes:
      - ./backend:/usr/src/app    

  database:
    container_name: database
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin1234
      POSTGRES_DB: mydb
    ports:
      - 5432:5432  
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:          